### ISSUE TITLE
Support using Java 11

### ISSUE THREAD

**Issue by chriscarpenter12** [jenkinsci/nexus-platform-plugin#133]
While using the Nexus Platform plugin for Jenkins using Java 11 there’s an error configuring a Nexus Repository Manager 3.x Server. Upon clicking “Test connection” there’s an error requiring JAXB-API. Reverting the Jenkins instance back to Java 8 using the same configuration works properly.

System Information:
Jenkins 2.235.5 - Java openjdk version “11.0.9”
Nexus Platform Plugin 3.9.20201109-154552.99ba8b9
Nexus OSS 3.28.1-01

While investigating this error I came across this [PR](https://github.com/jenkinsci/nexus-platform-plugin/pull/75) adding Java 11 support by adding the missing JAXB dependencies, but it was closed and never merged.

![nexus-error](https://user-images.githubusercontent.com/458486/99588094-15b77d00-29b8-11eb-8710-aa89d26332ce.png)

[nexus-error.txt](https://github.com/jenkinsci/nexus-platform-plugin/files/5562737/nexus-error.txt)

**Comment by mpuglin** [comment]
Thank you for using our plugin.  We have added this issue to our internal backlog and will prioritize it against that work.

**Comment by mpuglin** [comment]
Java 11 compatibility provided with release  jenkins-3.10.20201208-151941.d953318
