### ISSUE TITLE
Pipeline stage should also be marked as unstable/failure, not only entire build

### ISSUE THREAD

**Issue by b8** [jenkinsci/nexus-platform-plugin#153]
### Dependencies

Scripted or declarative pipeline build job.

### Feature Request

I'd like to see the current step marked as unstable or failed, not only the entire build. Currently, it's quite cumbersome to find out why a build has failed or become unstable because the current stage isn't marked, only the entire build.

**Comment by eduard-tita** [comment]
Thank you for creating this issue. Unfortunately we were not able to replicate the above behavior. If you could add an example of a scripted pipeline for us to look at, we would like to investigate it further.
