### ISSUE TITLE
jenkins job is successful only, if we provide nx-admin credentials

### ISSUE THREAD

**Issue by Abhilash-sandupatla** [jenkinsci/nexus-platform-plugin#170]
I have a repository. I have given admin privileges of that repository to a user. By using that user credentials, Jenkins job is failing.
Error:-
npm ERR! code E401
npm ERR! Unable to authenticate, need: BASIC realm="Sonatype Nexus Repository Manager"
npm verb exit [ 1, true ]
npm http fetch GET 401 https://pie-nexus.xxxxxx.com/repository/pie-npm-group/react-router-dom/-/react-router-dom-5.3.0.tgz 5061ms

But, when I give nx-admin role to that user, jerkins job is working.

My doubt is, Does it require nx-admin credentials, to run Jenkins job for nexus automation (or) requires only particular repository admin access

**Comment by eduard-tita** [comment]
As far as I can tell this issue is not related to the Nexus Platform Plugin. I'm closing this issue for now.
