### ISSUE TITLE
use nexusPolicyEvaluation to push to different organization in NexusIQ

### ISSUE THREAD

**Issue by basilboonk** [jenkinsci/nexus-platform-plugin#177]
We are using `nexusPolicyEvaluation `  to scan our images with NexusIQ lifecycle. Currently, it's going to the default organization which is mentioned automatic application section.

Is it possible to add an option to mention the organization while doing the scan ?

The rationale behind this is to set the policy based on organizations in NexusIQ.

```
Details:
Nexus platform plugin version : 3.11.20210420-142258.bdfc332
Jenkins version: 2.289.1
NexusIQ lifecycle version : 128
```

Sample code which we are using as of now

```
try {
    def policyEvaluation = nexusPolicyEvaluation failBuildOnNetworkError: false,
      iqApplication: "${name}_${tag}",
      iqScanPatterns: [[scanPattern: '*.tar']],
      iqStage: "${imgLifecycleStage}"
    echo "Successfully scanned image ${imgId}: ${policyEvaluation.applicationCompositionReportUrl}"
    return policyEvaluation
  }
```

**Comment by cniweb** [comment]
This option to mention the organization while doing the scan is also very important for us!
:+1:

**Comment by cniweb** [comment]
To supplement, there is also an idea for this at Sonatype:
https://ideas.sonatype.com/ideas/IDEAS-I-1343

**Comment by RajasGujarathi** [comment]
Do we have some updates on this feature? We are eagerly waiting for it 🤞

**Comment by eduard-tita** [comment]
We are working on it. I'll post here when it's released.

**Comment by eduard-tita** [comment]
Hi all. 

Nexus platform plugin for Jenkins supports an optional [organization ID parameter](https://help.sonatype.com/iqserver/integrations/nexus-and-continuous-integration/nexus-platform-plugin-for-jenkins#NexusPlatformPluginforJenkins-ProjectStepProjectStep) as of version [3.16.444.v52b_e5e2db_503](https://plugins.jenkins.io/nexus-jenkins-plugin/#plugin-content-316444v52b_e5e2db_503-september-22-2022).

Pleas note that the minimum required version of IQ Server is 144. Most likely you will need to upgrade your IQ Server first and then you can try the new organization ID parameter.
