### ISSUE TITLE
No pom file for version 3.13.20220124-204320.8222771

### ISSUE THREAD

**Issue by cristian-aldea** [jenkinsci/nexus-platform-plugin#181]
My issues doesn't really fit under any of the categories for this repository. I needed to get in contact with someone who maintains this plugin since we are having trouble downloading it from https://repo.jenkins-ci.org

Currently our team maintains an internal Jenkins Plugin Mirror which downloads plugins for our customers to use. However for nexus-jenkins-plugin, the version our plugin mirror tries to download doesn't have the .pom file it expects, and then crashes.

It tries to download the plugin from here: https://repo.jenkins-ci.org/artifactory/releases/org/sonatype/nexus/ci/nexus-jenkins-plugin/3.13.20220124-204320.8222771/

For some reason that is the only version I could find of your plugin which doesn't have anything but a .hpi file (no pom, no jar). Please direct me to someone I can contact about this issue

**Comment by eduard-tita** [comment]
Thank you for reporting this issue. 

That was an unfortunate instance related to https://repo.jenkins-ci.org/ having disk space issues, which has been remediated in the mean time. On top of that, we moved our release process from an in-house one to the jenkins.io recommended release process (GitHub actions base). I'm closing this issue for now.
