### ISSUE TITLE
Support using individuel project's nexus configuration instead of nexusInstanceId

### ISSUE THREAD

**Issue by ridaeh** [jenkinsci/nexus-platform-plugin#247]
### What feature do you want to see added?

Hi,
It will be nice to give the possibility for the projects to add their own  nexus configuration (serverUrl, credentialsId) instead of the Global nexusInstantId .

Something like this will be more helpfull: 

`
createTag  credentialsId: 'projects-user', serverUrl: 'https://nexux' , tagAttributesJson: '{}', tagName: 'build-125' 
`

**Comment by eduard-tita** [comment]
Thank you for creating this issue.

If you have a use case for altering the existing behaviour, please file a product idea, so our product managers will be informed and can prioritize accordingly.

Sonatype registered support account contacts can go here to file an idea: https://ideas.sonatype.com/
